FROM antimodes201/steamcmd-base:latest
MAINTAINER antimodes201

# Set some Variables
ARG GAME_PORT_1=7787
ARG GAME_PORT_2=7788
ARG QUERY_PORT_1=27165
ARG QUERY_PORT_2=27165
ARG RCON_PORT=21114

ENV BRANCH "public"
ENV INSTANCE_NAME "default"
ENV GAME_PORT_1 $GAME_PORT_1
ENV GAME_PORT_2 $GAME_PORT_2
ENV QUERY_PORT_1 $QUERY_PORT_1
ENV QUERY_PORT_2 $QUERY_PORT_2
ENV RCON_PORT $RCON_PORT
ENV MAX_PLAYERS 80
ENV RANDOM = ALWAYS
ENV BETA_NAME ""
ENV BETA_PASSWORD "" 
ENV ADDITIONAL_ARGS ""
ENV ADMIN ""
ENV TZ "America/New_York"


ADD start.sh /scripts/start.sh

# Expose some port
EXPOSE $GAME_PORT_1/udp
EXPOSE $GAME_PORT_2/udp
EXPOSE $QUERY_PORT_2/udp
EXPOSE $QUERY_PORT_2/tcp
EXPOSE $QUERY_PORT_2/udp
EXPOSE $RCON_PORT/tcp
EXPOSE $RCON_PORT/udp

CMD ["/scripts/start.sh"]

